[WARNING]:[2017-04-01 11:27:20]:[3057253232]:[42:RECV():new_core/test_connect.cpp] throw exception error the client close the socket(46)
[WARNING]:[2017-04-01 11:27:20]:[3057253232]:[41:on_cb():new_core/common_connect.cpp] caught exception info:the client close the socket(46)
[WARNING]:[2017-04-01 11:55:23]:[3057040240]:[42:RECV():new_core/test_connect.cpp] throw exception error the client close the socket(46)
[WARNING]:[2017-04-01 11:55:23]:[3057040240]:[41:on_cb():new_core/common_connect.cpp] caught exception info:the client close the socket(46)
[WARNING]:[2017-04-01 11:56:35]:[3046550384]:[42:RECV():new_core/test_connect.cpp] throw exception error the client close the socket(46)
[WARNING]:[2017-04-01 11:56:35]:[3046550384]:[41:on_cb():new_core/common_connect.cpp] caught exception info:the client close the socket(46)
[WARNING]:[2017-04-01 16:48:46]:[3065920368]:[43:RECV():new_core/test_connect.cpp] throw exception error the client close the socket(48)
[WARNING]:[2017-04-01 16:48:46]:[3065920368]:[41:on_cb():new_core/common_connect.cpp] caught exception info:the client close the socket(48)
[WARNING]:[2017-04-01 16:55:28]:[3065920368]:[43:RECV():new_core/test_connect.cpp] throw exception error the client close the socket(48)
[WARNING]:[2017-04-01 16:55:28]:[3065920368]:[41:on_cb():new_core/common_connect.cpp] caught exception info:the client close the socket(48)
[WARNING]:[2017-04-01 16:55:53]:[3051354992]:[43:RECV():new_core/test_connect.cpp] throw exception error the client close the socket(48)
[WARNING]:[2017-04-01 16:55:53]:[3051354992]:[41:on_cb():new_core/common_connect.cpp] caught exception info:the client close the socket(48)
[WARNING]:[2017-04-01 16:59:42]:[3065920368]:[43:RECV():new_core/test_connect.cpp] throw exception error the client close the socket(50)
[WARNING]:[2017-04-01 16:59:42]:[3065920368]:[41:on_cb():new_core/common_connect.cpp] caught exception info:the client close the socket(50)
[WARNING]:[2017-04-01 17:12:07]:[3051354992]:[43:RECV():new_core/test_connect.cpp] throw exception error the client close the socket(50)
[WARNING]:[2017-04-01 17:12:07]:[3051354992]:[41:on_cb():new_core/common_connect.cpp] caught exception info:the client close the socket(50)
[WARNING]:[2017-04-01 17:23:54]:[3030375280]:[43:RECV():new_core/test_connect.cpp] throw exception error the client close the socket(51)
[WARNING]:[2017-04-01 17:23:54]:[3030375280]:[41:on_cb():new_core/common_connect.cpp] caught exception info:the client close the socket(51)
[WARNING]:[2017-04-01 17:23:57]:[3040865136]:[43:RECV():new_core/test_connect.cpp] throw exception error the client close the socket(50)
[WARNING]:[2017-04-01 17:23:57]:[3040865136]:[41:on_cb():new_core/common_connect.cpp] caught exception info:the client close the socket(50)
[WARNING]:[2017-04-01 18:03:19]:[3065920368]:[50:RECV():new_core/test_connect.cpp] throw exception error this socket occur fatal error Connection reset by peer
[WARNING]:[2017-04-01 18:03:19]:[3065920368]:[41:on_cb():new_core/common_connect.cpp] caught exception info:this socket occur fatal error Connection reset by peer
[WARNING]:[2017-04-01 18:04:35]:[3065920368]:[43:RECV():new_core/test_connect.cpp] throw exception error the client close the socket(50)
[WARNING]:[2017-04-01 18:04:35]:[3065920368]:[41:on_cb():new_core/common_connect.cpp] caught exception info:the client close the socket(50)
